steps:
# Step 1: Submit source code
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_IMAGE_NAME:$_IMAGE_TAG', '.']

# Step 2: Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_IMAGE_NAME:$_IMAGE_TAG']

# Step 3: Generate deployment file
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'cd /workspace && envsubst < k8s.yaml > deploy.yaml'

# Step 4: Deploy to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=deploy.yaml
  - --location=us-central1
  - --cluster=kabuda-backend

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _IMAGE_NAME: us-west2-docker.pkg.dev/careful-granite-450104-s7/kabuda-backend/api-server
  _IMAGE_TAG: latest
