apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: us-west2-docker.pkg.dev/$GCLOUD_PROJECT_ID/kabuda-backend/api-server:$GCLOUD_IMAGE_TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: api-server-config
            - secretRef:
                name: api-server-secrets
      restartPolicy: Always
