[project]
name = "Kabuda-Backend"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "PookieBuns", email = "allenyuchen@hotmail.com"},
]
dependencies = ["fastapi>=0.115.8", "uvicorn>=0.34.0"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[dependency-groups]
lint = [
    "mypy>=1.15.0",
]
